Allow python 3.4 tests to fail in travis
Pip and arrow are both complaining about the presence of v3.4.

From the travis log

0.82s$ pip install .
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Processing /home/travis/build/davesteele/topydo
Collecting arrow>=0.7.0 (from topydo==0.13)
  Downloading https://files.pythonhosted.org/packages/a2/6a/a3d20e80ee4fee7c55c022fb28d52239bd01171edd3c137dd1e2ef8b2a20/arrow-0.14.2-py2.py3-none-any.whl
ERROR: arrow requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8

The command "pip install ." failed and exited with 1 during .

Your build has been stopped.